apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: wikator/movies-api:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: CloudinarySettings_ApiKey
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: CloudinarySettings_ApiKey
        - name: CloudinarySettings_ApiSecret
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: CloudinarySettings_ApiSecret
        - name: CloudinarySettings_CloudName
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: CloudinarySettings_CloudName
        - name: InitialPassword
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: InitialPassword
        - name: MqttPassword
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MqttPassword
        - name: TokenKey
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: TokenKey
        - name: Db_Password
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Db_Password
        - name: Db_UserName
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Db_UserName
        - name: Db_Server
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Db_Server