apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-db
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
      - name: backend-db
        image: neo4j:latest
        envFrom:
        - configMapRef:
            name: neo4j-config
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: "bolt"
        volumeMounts:
        - mountPath: /data
          name: neo4j-data
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: backend-db-secrets
              key: Credentials
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /browser/
            port: 7474
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /browser/
            port: 7474
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc