# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: backend-db-hpa
#   namespace: my-app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: StatefulSet
#     name: backend-db
#   minReplicas: 1
#   maxReplicas: 20
#   targetCPUUtilizationPercentage: 50