apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
  namespace: my-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/neo4j"
